// src/components/hr/staff/StaffPayslipPanel.tsx

import { useEffect, useState } from "react";
import { useHrStore } from "@/store/hr/useHrStore";
import SectionCard from "@/components/hr/shared/SectionCard";
import EmptyState from "@/components/hr/shared/EmptyState";
import { PayslipStatusBadge } from "@/components/hr/shared/StatusBadge";
import PayslipDetailModal from "@/components/hr/shared/PayslipDetailModal";
import type { Payslip } from "@/types/hr-types";
import { FileText, Eye, DollarSign, TrendingUp, RefreshCw } from "lucide-react";

const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export default function StaffPayslipPanel() {
  const { myPayslips, isLoading, fetchMyPayslips } = useHrStore();
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
  const [viewPayslip, setViewPayslip] = useState<Payslip | null>(null);

  useEffect(() => {
    fetchMyPayslips(selectedYear);
  }, [selectedYear]);

  const totalEarned = myPayslips
    .filter((p) => p.status === "PAID")
    .reduce((s, p) => s + p.netPay, 0);

  const latestPayslip = myPayslips[0];

  return (
    <div className="space-y-6">
      {/* Summary */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="bg-gradient-to-br from-emerald-600 to-emerald-700 rounded-xl p-5 text-white">
          <div className="flex items-center gap-2 mb-3">
            <DollarSign className="w-5 h-5 text-emerald-200" />
            <p className="text-sm font-medium text-emerald-100">
              Total Earned ({selectedYear})
            </p>
          </div>
          <p className="text-3xl font-black">${totalEarned.toLocaleString()}</p>
          <p className="text-emerald-200 text-xs mt-1">
            From {myPayslips.filter((p) => p.status === "PAID").length} paid
            payslips
          </p>
        </div>

        <div className="bg-white border border-slate-200 rounded-xl p-5">
          <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">
            Latest Payslip
          </p>
          {latestPayslip ? (
            <>
              <p className="text-2xl font-bold text-slate-900">
                ${latestPayslip.netPay.toLocaleString()}
              </p>
              <p className="text-xs text-slate-400 mt-0.5">
                {MONTHS[latestPayslip.month - 1]} {latestPayslip.year}
              </p>
            </>
          ) : (
            <p className="text-sm text-slate-400">No payslips yet</p>
          )}
        </div>

        <div className="bg-white border border-slate-200 rounded-xl p-5">
          <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">
            Payslips Count
          </p>
          <p className="text-2xl font-bold text-slate-900">
            {myPayslips.length}
          </p>
          <p className="text-xs text-slate-400 mt-0.5">{selectedYear}</p>
        </div>
      </div>

      {/* Filter */}
      <div className="flex items-center gap-2">
        <span className="text-sm text-slate-500">Year:</span>
        <select
          value={selectedYear}
          onChange={(e) => setSelectedYear(Number(e.target.value))}
          className="text-sm border border-slate-200 rounded-lg px-3 py-1.5 bg-white text-slate-700 outline-none"
        >
          {[2024, 2025, 2026].map((y) => (
            <option key={y} value={y}>
              {y}
            </option>
          ))}
        </select>
      </div>

      <SectionCard
        title="Payslip History"
        subtitle={String(selectedYear)}
        noPadding
      >
        {isLoading ? (
          <div className="flex items-center justify-center py-16">
            <RefreshCw className="w-5 h-5 text-slate-400 animate-spin" />
          </div>
        ) : myPayslips.length === 0 ? (
          <EmptyState
            icon={FileText}
            title="No payslips yet"
            description="Your payslips will appear here once generated by your admin"
          />
        ) : (
          <div className="divide-y divide-slate-100">
            {myPayslips.map((p) => (
              <div
                key={p.id}
                className="flex items-center gap-4 px-5 py-4 hover:bg-slate-50/50 transition-colors"
              >
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-100 to-violet-200 flex items-center justify-center shrink-0">
                  <FileText className="w-5 h-5 text-violet-600" />
                </div>

                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold text-slate-800">
                    {MONTHS[p.month - 1]} {p.year}
                  </p>
                  <div className="flex items-center gap-3 mt-0.5">
                    <span className="text-xs text-slate-400">
                      Basic: ${p.basicSalary.toLocaleString()}
                    </span>
                    {p.totalAllowances > 0 && (
                      <span className="text-xs text-emerald-600">
                        +${p.totalAllowances.toLocaleString()}
                      </span>
                    )}
                    {p.totalDeductions > 0 && (
                      <span className="text-xs text-rose-500">
                        -${p.totalDeductions.toLocaleString()}
                      </span>
                    )}
                  </div>
                </div>

                <div className="text-right shrink-0">
                  <p className="text-base font-bold text-slate-900">
                    ${p.netPay.toLocaleString()}
                  </p>
                  <PayslipStatusBadge status={p.status} />
                </div>

                <button
                  onClick={() => setViewPayslip(p)}
                  className="p-2 text-slate-400 hover:text-slate-700 hover:bg-slate-100 rounded-lg transition-colors shrink-0"
                >
                  <Eye className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>
        )}
      </SectionCard>

      {viewPayslip && (
        <PayslipDetailModal
          payslip={viewPayslip}
          onClose={() => setViewPayslip(null)}
        />
      )}
    </div>
  );
}
